# frozen_string_literal: true

module Ingest
  # Decides whether a message should become a ticket at all.
  #
  # This runs before anything is created, because the failure mode it prevents
  # is the classic one: Spool auto-replies to an out-of-office, whose sender
  # auto-replies to that, forever, with a new ticket each round. Every rule here
  # is cheap and every one of them is load-bearing.
  #
  # Returns nil to accept, or a short string reason to reject.
  module LoopGuard
    # RFC 3834. Any value other than "no" means the message was generated
    # automatically — auto-replied, auto-generated, or auto-notified.
    AUTO_SUBMITTED = "auto-submitted"

    # Non-standard but near-universal: bulk mail, mailing lists, and most
    # vacation responders set one of these.
    BULK_PRECEDENCE = %w[bulk list junk auto_reply].freeze

    # Microsoft's marker. Its presence at all means "this is automated".
    SUPPRESS_HEADERS = %w[
      x-auto-response-suppress
      x-autoreply
      x-autorespond
      x-autogenerated
    ].freeze

    # Mailing list traffic. A support address subscribed to a list would
    # otherwise open a ticket per post.
    LIST_HEADERS = %w[list-id list-unsubscribe list-post].freeze

    # Local parts that are never a person with a support request.
    ROBOT_LOCAL_PARTS = %w[
      mailer-daemon postmaster no-reply noreply donotreply do-not-reply
      bounce bounces notifications notification
    ].freeze

    module_function

    def reject_reason(mail)
      auto_submitted(mail) ||
        precedence(mail) ||
        suppression_header(mail) ||
        mailing_list(mail) ||
        bounce(mail) ||
        robot_sender(mail) ||
        self_sent(mail)
    end

    def auto_submitted(mail)
      value = header(mail, AUTO_SUBMITTED)
      return nil if value.blank?
      return nil if value.casecmp("no").zero?
      "auto-submitted: #{value}"
    end

    def precedence(mail)
      value = header(mail, "precedence")
      return nil if value.blank?
      BULK_PRECEDENCE.include?(value.downcase) ? "precedence: #{value}" : nil
    end

    def suppression_header(mail)
      found = SUPPRESS_HEADERS.find { |h| header(mail, h).present? }
      found ? "suppression header: #{found}" : nil
    end

    def mailing_list(mail)
      found = LIST_HEADERS.find { |h| header(mail, h).present? }
      found ? "mailing list header: #{found}" : nil
    end

    # A null Return-Path (`<>`) is the envelope sender every bounce is required
    # to use, and a delivery-status report is what a bounce carries. Either one
    # on its own is enough.
    def bounce(mail)
      return "null return-path (bounce)" if header(mail, "return-path").to_s.strip == "<>"

      content_type = mail.content_type.to_s.downcase
      return "delivery-status report" if content_type.include?("report-type=delivery-status")
      return "delivery-status report" if content_type.include?("multipart/report")

      nil
    end

    def robot_sender(mail)
      local = from_address(mail).to_s.split("@").first.to_s.downcase
      return nil if local.blank?
      ROBOT_LOCAL_PARTS.include?(local) ? "robot sender: #{local}" : nil
    end

    # Spool's own outbound mail arriving back in the support mailbox — because
    # the From: header stays support@ so replies land in the right place, a Bcc
    # or a list echo can deliver our own message straight back to us. The
    # Message-ID is ours and already in the database, so recognising it is exact
    # rather than heuristic.
    def self_sent(mail)
      message_id = normalized_message_id(mail)
      return nil if message_id.blank?

      return "own outbound message echoed back" if
        ::Message.outbound.where(message_id: message_id).exists?

      nil
    end

    def header(mail, name)
      mail[name]&.to_s
    rescue
      # A malformed header field can raise inside the mail gem's parser. An
      # unreadable header is not a reason to reject the message.
      nil
    end

    def from_address(mail)
      mail.from&.first
    rescue
      nil
    end

    def normalized_message_id(mail)
      # The mail gem strips the angle brackets; Spool stores them, since that's
      # what In-Reply-To and References carry.
      id = mail.message_id
      id.present? ? "<#{id}>" : nil
    rescue
      nil
    end
  end
end
