# frozen_string_literal: true

module Ingest
  # Decides which ticket an inbound message belongs to.
  #
  # Three strategies, strongest first. The first two match on Message-IDs, which
  # are unguessable and were generated by Spool, so a hit is proof. The third
  # matches on a number a human can see and retype, so it carries an extra
  # check. See docs/ingest.md.
  module Threader
    module_function

    # Returns an existing Ticket, or nil to open a new one.
    def find_ticket(mail, customer)
      by_in_reply_to(mail) ||
        by_references(mail) ||
        by_subject_tag(mail, customer)
    end

    def by_in_reply_to(mail)
      ticket_for_message_id(header_ids(mail, "in-reply-to").first)
    end

    # References carries the whole ancestry, oldest first. Walk it backwards so
    # a reply lands on the ticket of the nearest ancestor Spool knows about,
    # which matters when a thread has been forwarded between tickets.
    def by_references(mail)
      header_ids(mail, "references").reverse_each do |id|
        ticket = ticket_for_message_id(id)
        return ticket if ticket
      end
      nil
    end

    # Last resort, for clients that drop In-Reply-To and References — which
    # happens, particularly when someone replies from a webmail interface after
    # forwarding the thread to themselves.
    #
    # Guarded on the customer matching, because unlike a Message-ID a "[#42]" is
    # visible in the subject line and trivially retyped: without the check, a
    # stranger quoting a forwarded email would append themselves to another
    # customer's ticket. A mismatch opens a new ticket instead, which an agent
    # can see and merge mentally — the safe direction to fail.
    def by_subject_tag(mail, customer)
      match = mail.subject.to_s.match(Ticket::SUBJECT_TAG)
      return nil unless match

      ticket = Ticket.find_by(id: match[1])
      return nil unless ticket
      return nil unless ticket.customer_id == customer.id

      ticket
    end

    def ticket_for_message_id(message_id)
      return nil if message_id.blank?
      ::Message.find_by(message_id: message_id)&.ticket
    end

    # Pulls every <...> token out of a header. In-Reply-To is specified as a
    # single id but arrives with several often enough to be worth handling, and
    # References is a whitespace-separated list.
    def header_ids(mail, name)
      raw = begin
        mail[name]&.to_s
      rescue
        nil
      end
      return [] if raw.blank?

      raw.scan(/<[^>]+>/)
    end
  end
end
